import { useEffect, useMemo, useRef, useState } from "react";
import { useTranslation } from "react-i18next";
import type { InsightMilestone, TimelineBucket } from "@/types";
import { PlayIcon, PauseIcon, RotateCcwIcon } from "@/components/common/Icons";
import { createTimelineFrames } from "@/utils/insights";
import { exportInsights, makeExportFileName } from "@/utils/exportInsights";
import { useToastStore } from "@/stores/toastStore";

export function ProgressTimeline({ timeline, milestones = [] }: { timeline: TimelineBucket[]; milestones?: InsightMilestone[] }) {
  const { t } = useTranslation(); const toast = useToastStore(); const svgRef = useRef<SVGSVGElement>(null); const [index, setIndex] = useState(Math.max(0, timeline.length - 1)); const [playing, setPlaying] = useState(false); const [speed, setSpeed] = useState(1); const [exporting, setExporting] = useState(false);
  useEffect(() => { if (!playing || !timeline.length) return; const id = window.setInterval(() => setIndex((v) => v >= timeline.length - 1 ? (setPlaying(false), v) : v + 1), 900 / speed); return () => clearInterval(id); }, [playing, speed, timeline.length]);
  const current = timeline[index]; const max = Math.max(1, ...timeline.map((b) => b.cumulative_commits));
  const points = useMemo(() => timeline.map((b, i) => `${(i / Math.max(1, timeline.length - 1)) * 100},${100 - b.cumulative_commits / max * 85}`).join(" "), [timeline, max]);
  const svgFor = (bucket: TimelineBucket) => { const bucketMax = Math.max(1, ...timeline.map((b) => b.cumulative_commits)); const point = timeline.map((b, i) => `${(i / Math.max(1, timeline.length - 1)) * 100},${100 - b.cumulative_commits / bucketMax * 85}`).join(" "); const visible = timeline.findIndex((b) => b.period === bucket.period); const active = timeline.slice(0, visible + 1).map((b, i) => `${(i / Math.max(1, timeline.length - 1)) * 100},${100 - b.cumulative_commits / bucketMax * 85}`).join(" "); return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" width="1200" height="480"><polyline points="${point}" fill="none" stroke="#888" stroke-width="1.5"/><polyline points="${active}" fill="none" stroke="#4f8cff" stroke-width="2.5"/></svg>`; };
  const runExport = async (format: "svg" | "png" | "gif") => { if (exporting || !timeline.length) return; setExporting(true); try { const path = format === "gif" ? await exportInsights({ format, frames: createTimelineFrames(timeline).map((bucket) => ({ svg: svgFor(bucket) })), frameRate: 8, fileName: makeExportFileName("repository", "timeline", format) }) : await exportInsights({ format, svg: svgRef.current || svgFor(current), fileName: makeExportFileName("repository", "timeline", format) }); if (path) toast.success(`${format.toUpperCase()} 导出成功`); } catch (e) { toast.error(e instanceof Error ? e.message : "导出失败"); } finally { setExporting(false); } };
  return <section className="rounded-lg border border-border bg-bg-surface p-4"><div className="flex items-center justify-between mb-3"><h2 className="font-medium">项目进展时间线</h2><div className="flex gap-2"><button type="button" onClick={() => setPlaying((v) => !v)} aria-label={playing ? "暂停" : "播放"}>{playing ? <PauseIcon size={14} /> : <PlayIcon size={14} />}</button><button type="button" onClick={() => { setIndex(0); setPlaying(false); }} aria-label="重新播放"><RotateCcwIcon size={14} /></button><select value={speed} onChange={(e) => setSpeed(Number(e.target.value))} className="bg-bg-base border border-border rounded text-xs"><option value="0.5">0.5x</option><option value="1">1x</option><option value="2">2x</option></select>{(["svg", "png", "gif"] as const).map((format) => <button key={format} type="button" disabled={exporting || !timeline.length} onClick={() => void runExport(format)} className="text-xs rounded border border-border px-2 py-1 disabled:opacity-50">{exporting ? t("common.loading") : format.toUpperCase()}</button>)}</div></div>{!timeline.length ? <p className="text-sm text-text-muted">暂无时间线记录</p> : <><svg ref={svgRef} viewBox="0 0 100 100" width="1200" height="480" className="w-full h-40" role="img" aria-label="累计提交进展"><polyline points={points} fill="none" stroke="currentColor" strokeWidth="1.5" className="text-accent" />{milestones.map((m) => <text key={m.hash} x="2" y="12" className="fill-text-muted text-[3px]">{m.name}</text>)}</svg><input className="w-full" type="range" min="0" max={timeline.length - 1} value={index} onChange={(e) => setIndex(Number(e.target.value))} aria-label="时间线进度" /><p className="text-xs text-text-muted">{current?.period} · 累计 {current?.cumulative_commits ?? 0} 次提交 · {current?.cumulative_contributors ?? 0} 位贡献者</p></>}</section>;
}
